### ISSUE TITLE
PLS Updata this great cheat for the game updata in 4.29/2024 PLSPLS

### ISSUE THREAD

**Issue by AdrianVitoria12** [Krenity/Mordhau-Cheat#2]
Just for the new updata in 4.29/2024   This great cheat was down. just cause it will be a error about the Uint64, it says this number too big or too small for this game. PLSPLS Updata this cheat!!!! THX SO MUCH!!!

**Comment by AdrianVitoria12** [comment]
and im steam, i tried this in epic, it could be opened, but it didnt work. maybe it cant be injected in game. pls!!!! updata!!!! it is siginificant for me!!! THX SO MUCH!!!!

**Comment by Krenity** [comment]
**Updated!**

**Comment by AdrianVitoria12** [comment]
> **Updated!**

THX SO MUCH!!!! I wanna pay u some money for this. Can u use Alipay?
